[study_0000]
name = "シード値不変性"
link = ""
note = """
シード値によってその他のハイパーパラメータの最適値が変わらないことを確認する．
変わらないならば，シード値を固定してもよい．
"""
num_trials = 1000
objective = "val/receiver_loss"
direction = "minimize"

[study_0001]
name = "チャネルの帯域幅と伝達能力の関係"
link = ""
note = """
チャネルの長さと語彙数を変えたときの伝達能力の変化を調べる．
"""
